[package]
name = "jiminy-entrypoint"
version.workspace = true
edition.workspace = true

[features]
default = ["allocator", "panic"]
allocator = []
panic = ["dep:jiminy-syscall"]

[dependencies]
jiminy-account = { workspace = true }
jiminy-syscall = { workspace = true, optional = true }

