[package]
name = "jiminy-test-utils"
version.workspace = true
edition.workspace = true

[target.'cfg(not(target_os = "solana"))'.dependencies]
proptest = { workspace = true }
solana-logger = { workspace = true }
