[package]
name = "jiminy-sysvar-clock"
version.workspace = true
edition.workspace = true

[dependencies]
const-crypto = { workspace = true }
jiminy-sysvar = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
proptest = { workspace = true }
solana-clock = { workspace = true }
