[package]
name = "jiminy-cpi"
version.workspace = true
edition.workspace = true

[dependencies]
jiminy-account = { workspace = true }
jiminy-pda = { workspace = true }
jiminy-program-error = { workspace = true }
jiminy-syscall = { workspace = true }
